### ISSUE TITLE
Getting this error on installing Erlang on RHEL8

### ISSUE THREAD

**Issue by nitinsinghit** [rockandska/ansible-role-rabbitmq#18]
fatal: [172.26.126.248]: FAILED! => changed=false 
  msg: 'Failed to download metadata for repo ''rabbitmq_erlang'': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried'
  rc: 1
  results: []

**Comment by rockandska** [comment]
This error seems to concern https://github.com/rockandska/ansible-role-erlang and not this repository
